name: AfterlifeReloaded
main: me.gewoonhdgaming.afterlife.AfterLife
version: 2.1.3
author: [boykev,rens4000]
commands:
   al:
      description: Informatie over AfterLife
      aliases: [afterlife, alife]