name: AfterlifeReloaded
main: me.gewoonhdgaming.afterlife.AfterLife
version: 2.1.3
author: [boykev,rens4000]
commands:
   al:
      description: Informatie over AfterLife
      aliases: [afterlife, alife]
permissions:
    AfterLife.*:
        description: Toegang tot alle commando's van de AfterLife Plugin
        children:
            AfterLife.Admin: true
            AfterLife.user: true
    AfterLife.Admin:
        description: Geeft administrator rechten voor de plugin
        default: op
    AfterLife.user:
        description: Gebruikersrechten
        default: op